### ISSUE TITLE
ua-scorer.py is giving zero values

### ISSUE THREAD

**Issue by ritwikmishra** [juntaoy/universal-anaphora-scorer#2]
I cloned the repo and installed the requirements 

```python ua-scorer.py tests/TC-A.key tests/TC-A.key```

Notice: I have passed the same file as key and response (system). The output should be 1.0

Output

```
The scorer is evaluating  corferent markables, singletons, split-antecedents 
lea
Recall: 0.00  Precision: 0.00  F1: 0.00
muc
Recall: 0.00  Precision: 0.00  F1: 0.00
bcub
Recall: 0.00  Precision: 0.00  F1: 0.00
ceafe
Recall: 0.00  Precision: 0.00  F1: 0.00
ceafm
Recall: 0.00  Precision: 0.00  F1: 0.00
blanc
Recall: 0.00  Precision: 0.00  F1: 0.00
CoNLL score: 0.00
```

**Comment by michnov** [comment]
Thanks for reporting the bug. There are actually two problems:

1. you are running `ua-scorer.py`, which accepts files in the UA format, on the files in the `tests` directory that are in the CoNLL 2012 format. For files in the CoNLL 2012 format, the `scorer.py` script has to be run instead. It is our fault, as this distinction is not documented in the `README.md`. However, we are working on the version 2.0, where there is only a single entry point and the input format can be specified by a command-line argument.
2. running `scorer.py` with default metrics would fail anyway on calling the `mentions` score calculation. It accepted only two arguments while it was given three. I fixed it in [f4adb45](https://github.com/juntaoy/universal-anaphora-scorer/commit/f4adb45bcb3e2359abeffc6316ce9f99f409ca56)

**Comment by michnov** [comment]
So running
```
python scorer.py tests/TC-A.key tests/TC-A.key
```
works now:
```
mentions   Recall: 100.00  Precision: 100.00  F1: 100.00
muc        Recall: 100.00  Precision: 100.00  F1: 100.00
bcub       Recall: 100.00  Precision: 100.00  F1: 100.00
ceafe      Recall: 100.00  Precision: 100.00  F1: 100.00
lea        Recall: 100.00  Precision: 100.00  F1: 100.00
CoNLL score: 100.00
```

**Comment by ritwikmishra** [comment]
@michnov can you give an example of UA format? is there any conll-->UA converter available?
